# Generated by Django 5.0.2 on 2024-02-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crea', '0004_propiedad_posible_es_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad_disponible',
            name='precio_pactado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True),
        ),
    ]
