# Generated by Django 5.0.2 on 2024-02-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crea', '0005_propiedad_disponible_precio_pactado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='email',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='password',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='username',
        ),
        migrations.AddField(
            model_name='empleado',
            name='apellido',
            field=models.CharField(max_length=144, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='area',
            field=models.CharField(choices=[('Aprobicionamiento', 'Aprobicionamiento'), ('Ventas', 'Ventas'), ('Tramites', 'Tramites')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='correo',
            field=models.EmailField(max_length=144, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(max_length=144, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(max_length=144, null=True),
        ),
    ]
